### ISSUE TITLE
leaflet - test.gpx not found 404 error

### ISSUE THREAD

**Issue by nicolehsieh** [nicolehsieh/Project2#1]
GET http://0.0.0.0:5000/test.gpx 404 (NOT FOUND) gpx.js:216 on 

I've been trying a another approach, using leaflet plugin for gpx file viewing. but for some reason, it's telling me it can't find the test.gpx file that is in the SAME directory. 

Anyone has any ideas??? 

Files is located in the [Testing folder](https://github.com/nicolehsieh/Project2/tree/master/Testing). 
To run with flask
-  download flask, 
- activate environment (. env/bin/activate), 
- and just run the program ($ python app.py)
- http://0.0.0.0:5000

The error shows up: http://0.0.0.0:5000/upload
To get there: just hit submit.

**Comment by juliestringham** [comment]
I can take a look at it. I don't have a lot of experience with leaflet, but
I have used it before.

**Comment by nicolehsieh** [comment]
Thanks! It's line 27 of leaf.html.

**Comment by juliestringham** [comment]
Alright, cool!

**Comment by nicolehsieh** [comment]
resolved
