### ISSUE TITLE
animating track problem

### ISSUE THREAD

**Issue by jhorn3** [nicolehsieh/Project2#6]
Error message: 
Uncaught TypeError: Cannot read property '_leaflet_id' of undefined leaflet.js:6

trying to include the leaflet plugin from https://github.com/openplans/Leaflet.AnimatedMarker/blob/master/src/AnimatedMarker.js
 had to paste the script directly into the leaf.html code, and now it gives the above error

**Comment by nicolehsieh** [comment]
try:     

``` javascript
<script type=text/javascript src="{{ url_for('static', filename='js/AnimatedMarker.js') }}"></script>
```

Note: AnimatedMarker.js is in `static/js/`

**Comment by nicolehsieh** [comment]
New Issue is the line that the animated Marker draws is not very accurate. For some reason it seems to go diagonal when there's a angle

**Comment by jhorn3** [comment]
Maybe that's something that adding the invisible simplified polyline on top would fix?

**Comment by nicolehsieh** [comment]
possibly. Can you try that and then let me know. 
But it should be drawing the path with the same longitude and latitudes lines tho...
